### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by sknebel** [keithjgrant/omnibear#11]
I tried this in Firefox. It doesn't quite work, since fetching pages from the extension without going through CORS requires permission for said pages. Adding `<all_urls>` to the permissions in `manifest.json` solved this, but I'm not sure it is the most elegant solution. 

After that, posting seemed to work, but I can't quite verify it since my endpoint has problems right now (but I see a successful POST request in the server logs).

EDIT: 
It is not yet possible in Firefox to ask for specific permissions that are not in the manifest (https://bugzilla.mozilla.org/show_bug.cgi?id=1197420), so unless there is something I'm missing the extension probably needs global permission to communicate with random URLs, as described above. I can submit a PR for this if you want, but such a trivial thing doesn't have to be attributed ;)

**Comment by keithjgrant** [comment]
Interesting. I had that permission at one point for the content_scripts that runs on each page, then realized Chrome didn't require it.

Did the UI work okay for you? When I tested in FirefoxNightly, the login input skipped characters if I typed quickly. Some issue with Preact and/or the keyup event.

**Comment by sknebel** [comment]
just tested again, I see the lost keypresses as well (I only had copy-pasted URLs before and thus didn't notice)

P.S.: What are the permissions for foo.com for?

**Comment by keithjgrant** [comment]
debugging code I should have deleted earlier :)  IIRC, I was trying to figure out what formatting/syntax Chrome wanted there.

**Comment by myfreeweb** [comment]
When developing [Transmitter](https://github.com/myfreeweb/transmitter), I've found that the worst offender here is Opera — they support the permissions request API but it does not work for user-specified hosts! (hosts that are unknown at manifest writing time)

Also hmm the bug is resolved fixed in nightly… I should test the permissions thing in my addon…

**Comment by keithjgrant** [comment]
Fixed as of 0.5.2. Submitted to Firefox Add-Ons library for review.
