### ISSUE TITLE
Post using x-www-form-urlencoded

### ISSUE THREAD

**Issue by keithjgrant** [keithjgrant/omnibear#12]
Posts are currently made using a `multipart/form-data` POST. To conform with the [micropub specification](https://www.w3.org/TR/micropub/#publishing-clients), this should instead be a `x-www-form-urlencoded` request.

**Comment by terminalpixel** [comment]
Well I think there really should be a go to micropub npm module that works frontend and backend. Would be very useful for a lot of people and maybe a few others would get involved contributing to it.

**Comment by keithjgrant** [comment]
That definitely makes sense.

**Comment by terminalpixel** [comment]
Well I made a start https://github.com/terminalpixel/micropub although I don't think it helps with this issue yet.

**Comment by grantcodes** [comment]
Got to a version 1 of this library now. It passes all the [micropub.rocks](http://micropub.rocks) tests when run server side. On the frontend it's likely to run into CORS issues but hopefully not inside a chrome plugin.

Anyway I could have a go at integrating it if you want?

**Comment by keithjgrant** [comment]
Have at it :) That would be awesome

**Comment by cweiske** [comment]
As you see in #31, Omnibear 0.6.0 sends `application/x-www-form-urlencoded` requests.

**Comment by keithjgrant** [comment]
@grantcodes This is taken care of now that we’re using `micropub-helper` correct? Should I close this issue?

**Comment by grantcodes** [comment]
Yes if you use `micropub.create(micropubObject, 'form')` then it sends `application/x-www-form-urlencoded` requests.

The other options are `json` and `multipart` if you ever need them
