### ISSUE TITLE
Authentication does not work with local auth servers

### ISSUE THREAD

**Issue by cweiske** [keithjgrant/omnibear#15]
Authentication does not work with local auth servers that are non internet-reachable.

My auth server redirects to omnibear.com, and then I only see:

>  Omnibear
> Authentication successful
>
> Retrieving access token...

And nothing happens because omnibear.com cannot reach `http://anoweco.bogo/` that is running here locally on my laptop.

I can basically not test the extension locally.

**Comment by keithjgrant** [comment]
I just released a version 0.4.2 yesterday that should have improved error messages when authentication goes wrong. Can you verify you’ve got this version and see if the displayed message gives any more info?

**Comment by cweiske** [comment]
I actually installed the extension this morning.

**Comment by keithjgrant** [comment]
Omnibear.com doesn’t have to reach your local server, only the browser extension does. I’ll have to do some experimentation and see if the extension needs additional permissions to access this.

**Comment by cweiske** [comment]
This still happens with 0.5.0

**Comment by keithjgrant** [comment]
On the “Retrieving access token page”, what is the full url in your url bar? Can you see if there are any console errors?

You will need to check the console of the "background page": 
1. Navigate to chrome://extensions/
2. Check "developer mode" box
3. Click "Inspect views: background page" under the Omnibear extension

**Comment by cweiske** [comment]
The full URL is `http://omnibear.com/auth/success/?code=ZW1vamk9JTVDMzYwJTVDMjM3JTVDMjIyJTVDMjUxJm1lPWh0dHBzJTNBJTJGJTJGY29tbWVudHBhcmEuZGUlMkZ1c2VyJTJGMy5odG0mc2NvcGU9cG9zdCtjcmVhdGUrZGVsZXRlK3VwZGF0ZSZzaWduYXR1cmU9RklYTUU%3D&me=https%3A%2F%2Fcommentpara.de%2Fuser%2F3.htm&state=very-secret-omnibear-state`

There is nothing to see in the background page's console.

**Comment by cweiske** [comment]
Works fine with Omnibear 0.6.0 on Firefox 55.
