### ISSUE TITLE
Authorisation works fine but extension doesn't publish

### ISSUE THREAD

**Issue by svnsbck** [keithjgrant/omnibear#20]
Hi,

I just learned about the extension and authorizing my blog went just fine. When publishing a post/reply/like I don't get any errors and a *post published* (or something similar), but the post never shows up on my blog, i.e. gets published. Any ideas of what might be wrong?

Any ideas?

**Comment by keithjgrant** [comment]
When the extension window is open, you can right-click on the window and select “Inspect” to open up DevTools. Can you see if there are any console errors?

Also, have you tested your micropub endpoint with any other tools like Quill? (https://quill.p3k.io/)

**Comment by svnsbck** [comment]
Hi, sorry for the late reply. I have tried Quill before and that works just fine (aside a few oddities). I have looked at the console and there don't seem to be any errors also *publishing* works fine and I get the *post published* confirmation. Using Wordpress with the Micropub plugin.

**Comment by keithjgrant** [comment]
When you open up DevTools, do you see any network errors? What kind of response do you get from your MicroPub endpoint?

**Comment by svnsbck** [comment]
Hi again! And yes, very late reply. Sorry about that.
I tried to the latest version of today (I believe it's 0.6) and in the console I see an Error 401 (non-authorized). The inspector closes immediately, I'm not sure is there more information hidden in there. 

I hope this helps. Is there anything that I can do on my end?

**Comment by tomasparks** [comment]
I am getting the same error 401,
the https://omnibear.com/auth/success/ page disappears too fast or stalls with:

> Authentication successful
> Retrieving access token...

**Comment by tomasparks** [comment]
firefox 57.0.1 (64-bit)
Chromium Version 63.0.3239.84 (Official Build) 
running on Ubuntu mate 16.04 (64-bit)

**Comment by keithjgrant** [comment]
Version 1.1.0 is publishing now to Chrome & Firefox stores. Once you get the update, can you

a) Enable the [new logging feature](https://omnibear.com/troubleshooting/), and
b) verify the issue still occurs

If you’re still having an issue, can you paste the relevant logs here?

**Comment by keithjgrant** [comment]
I believe we finally have a workaround for this, which I will get added into the next version. The core issue is in the wordpress plugin and is being addressed seperately (https://github.com/snarfed/wordpress-micropub/issues/133)

**Comment by dshanske** [comment]
The Core issue, is not easy to resolve if the individual is logged into the WordPress site.

**Comment by keithjgrant** [comment]
The latest version of Omnibear (1.2.0) has the workaround in place. It seems to be fixing it for most (but not all) WordPress users. It seems like the remaining issues are in the WordPress plugin. I'm closing this as I'm not sure there's anything else to be done on my end.
