### ISSUE TITLE
Autocompleted text in "Sign In" field discarded

### ISSUE THREAD

**Issue by cweiske** [keithjgrant/omnibear#21]
I want to sign omnibear into my website, so I type "htt", select the autosuggested URL and click "sign in".

Now the autocompleted text is somehow discarded, replaced with my manually typed text plus "http://" prepended. 

Omnibear should use the full text.

**Comment by keithjgrant** [comment]
Is this in Chromium?

**Comment by cweiske** [comment]
This works now on 0.6.0
