### ISSUE TITLE
Sign In does not work anymore

### ISSUE THREAD

**Issue by cweiske** [keithjgrant/omnibear#23]
When signing into omnibear with https://commentpara.de/, I only see the website with

> OmnibearAuthentication successful
> Retrieving access token...

And then nothing.

Happens with Chromium 60.

**Comment by keithjgrant** [comment]
I noticed similar behavior when trying to get the plugin working in Firefox. I’ll have to see if something in the permissions has changed

**Comment by keithjgrant** [comment]
Authentication is working for me using indieauth.com as my authentication endpoint. On the login screen, can you right-click -> "Inspect" and see if there are any console errors and/or network errors? On the Retrieving access token screen, what is in the url bar?

**Comment by keithjgrant** [comment]
Version 0.5.2 is publishing in the Chrome store now. This includes some additional permissions for the plugin that were required to make the plugin work in Firefox, and I’m hopeful these changes will fix Chromium as well.

**Comment by cweiske** [comment]
Omnibear 0.5.2 does neither work with Chromium 60.

There is no error (apart from the missing `favicon.ico`) on the omnibear.com site console.
There is no error in the background page console.

It stops as before at

> OmnibearAuthentication successful
> Retrieving access token...

The full URL in the address bar is:

http://omnibear.com/auth/success/?code=ZW1vamk9JTVDMzYwJTVDMjM3JTVDMjIyJTVDMjUxJm1lPWh0dHBzJTNBJTJGJTJGY29tbWVudHBhcmEuZGUlMkZ1c2VyJTJGMy5odG0mc2NvcGU9cG9zdCtjcmVhdGUrZGVsZXRlK3VwZGF0ZSZzaWduYXR1cmU9RklYTUU%3D&me=https%3A%2F%2Fcommentpara.de%2Fuser%2F3.htm&state=very-secret-omnibear-state

Btw, you can try with https://commentpara.de/ yourself - anyone can login there.

**Comment by grantcodes** [comment]
I'm having the same issue in the [vivaldi](https://vivaldi.com/) browser.

Same thing with stopping at "Retrieving access token..." and no errors to be seen anywhere. Works fine for me in chrome 60 though.

**Comment by grantcodes** [comment]
OK I know what is causing the issue, and it's a super easy fix in vivaldi but I don't know if it has any other side effects.

https://github.com/keithjgrant/omnibear/blob/347f24f6e83e0ce9a52cdcbc8fef98c0b38f90db/src/background.js#L86

If you remove `changeInfo.status === 'loading'` from this line it works fine, in vivaldi at least the status property is sent in a separate event. I'm not sure if removing that breaks anything but seems ok to me.

**Comment by keithjgrant** [comment]
Interesting. It looks like Vivaldi fires that event multiple times, each time passing only part of the change info:
![screen shot 2017-09-27 at 3 43 47 pm](https://user-images.githubusercontent.com/410794/30934153-ae40acec-a39a-11e7-917c-1bd4be5aa214.png)

So both the `status` and the `url` are not ever present at the same time to verify together. I’ll have to do a little experimenting to see if I really need that check for `loading`

**Comment by cweiske** [comment]
Omnibear 0.5.3  with Chromium continues to have the problem.

**Comment by keithjgrant** [comment]
0.6.0 has been published to both Chrome and Firefox extension stores. I’ve removed the check for "loading" status, so this should be working now. Let me know if this resolves the issue.

**Comment by cweiske** [comment]
With omnibear 0.6.0 and chromium 60  I get a JavaScript error on the background page:

```
background.js:1 POST chrome-extension://cjieakdeocmiimmphkfhdfbihhncoocn/null net::ERR_FILE_NOT_FOUND
(anonymous)	@	background.js:1
value	@	background.js:1
u	@	background.js:1
EventImpl.dispatchToListener	@	extensions::event_bindings:380
publicClassPrototype.(anonymous function)	@	extensions::utils:149
EventImpl.dispatch_	@	extensions::event_bindings:364
dispatchArgs	@	extensions::event_bindings:237
dispatchEvent	@	extensions::event_bindings:246
```

**Comment by keithjgrant** [comment]
Strange. I’m able to login in Version 60.0.3098.0 OS X 64bit using commentpara.de. I can do both the anonymous login and the named login. Are you on Windows or Mac?

I am having trouble posting via commentpara.de, but login is working.

Maybe try removing the extension entirely & reinstalling?

**Comment by cweiske** [comment]
I tried removing and re-installing the extension, but that did not help. I'm on Version 61.0.3163.79 (Official Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit)

**Comment by cweiske** [comment]
I can sign in on firefox 55 though. This is enough for me now, so you can close this issue if you don't want to work on this anyore.

**Comment by keithjgrant** [comment]
This might happen if you somehow had localStorage disabled. I use localStorage to save some of your auth settings, including the token endpoint. I wonder, do you have the "block sites from setting any data" option enabled?

![grxbu](https://user-images.githubusercontent.com/410794/31019877-374af852-a4ff-11e7-8558-d4db52a22a51.png)

**Comment by cweiske** [comment]
That was already enabled. I did now create a new clean profile, installed omnibear as only extension and it still gave the same error on the background page. Let's call it a day and see my machine as heisenbuggy.

**Comment by cweiske** [comment]
> I am having trouble posting via commentpara.de, but login is working.

This was a bug in commentpara.de - posting likes works now.
