### ISSUE TITLE
Add syndication targets

### ISSUE THREAD

**Issue by sebsel** [keithjgrant/omnibear#28]
Would be great to tell my blog to Tweet my post too, right from Omnibear, especially when it's in reply to a tweet.

You can get the targets by doing a GET to the endpoint with `?q=syndicate-to` and the access token. https://www.w3.org/TR/micropub/#syndication-targets

Then, when the button is pressed / checkbox is chosen, add a `mp-syndicate-to` field with the value of the button / syndication target, to the POST request. That gives the order to syndicate.

(I think my own blog and some other people support `syndicate-to` as the POST field, but that one is depricated. Better to use the new one.)

**Comment by grantcodes** [comment]
Should be quite possible. The `micropub-helper` library supports queries like this:
```
micropub.query('syndicate-to')
    .then(res => console.log(res['syndicate-to']));
```

**Comment by keithjgrant** [comment]
Done! I added a configuration option so the `mp-syndicate-to` field name can be modified in case your MP endpoint uses the legacy `syndicate-to` field name instead.

**Comment by skpy** [comment]
Sorry to revive this old issue, but I'm not seeing any syndication targets in Omnibear.  Both Quill and Indigenous for Android correctly show that my MP endpoint supports syndication to Twitter, but Omnibear provides nothing.  I've tried setting "Customize endpoint fields" from `mp-syndicate-to` to `syndicate-to` with no difference.

Is it the case that Omnibear syndicates to all available syndication targets without asking which for which ones to use?  That's fine, but is a different user experience from Quill and Indigenous for Android.  Either an explanation to that effect, or some UI to indicate this, would be helpful!
