### ISSUE TITLE
Save state / drafts / don't throw away my post when I click somewhere else

### ISSUE THREAD

**Issue by sebsel** [keithjgrant/omnibear#30]
When you type something, and then click on a webpage, Omnibear closes and discards the post.

Would be nice to save the post, so that when I open the window, I see the same thing again. (Just lost something because I didn't know, and losing posts while writing is sad.)

**Comment by keithjgrant** [comment]
OMG yes. Good call.

**Comment by cweiske** [comment]
I've lost some 20 words because I wanted to get a link from a new tab, and omnibear closed when I tabbed away.

**Comment by keithjgrant** [comment]
Fixed!
