### ISSUE TITLE
Incorrectly reporting http 500 replies as "successfully posted"

### ISSUE THREAD

**Issue by keithjgrant** [keithjgrant/omnibear#32]
I got a 500 from my micropub endpoint, but it displayed the normal "successfully posted" message, which is obviously incorrect. Something is slipping through the error handling for that request.

**Comment by grantcodes** [comment]
Yeah I just started noticing that too. It is because I didn't realise `fetch` will still resolve even if the http status is an error. I guess I may have to check the status codes in my micropub library

**Comment by keithjgrant** [comment]
Yeah, fetch only "fails" if the network request itself actually fails. You have to handle HTTP response codes separately. Make sure the micropub library exposes the response code somehow, so I can distinguish 500 codes from 400 codes.

**Comment by grantcodes** [comment]
Ok I have a new version of the `micropub-helper` library (1.2.0) that I push up to npm soon.

In this version it will throw errors if the endpoint doesn't return a 2xx status code.

Errors now come as objects like this:

```
{
  message: 'Human readable string',
  status: null or the http status code,
  error: null or further error information,
}
```

So you will be able to read if `err.status` is a 400 or 500 and do whatever you want.

Just let me know if you run into any problems or have questions.

**Comment by grantcodes** [comment]
So the `micropub-helper` update means that this will default to being an error and omnibear will flash the error message

**Comment by keithjgrant** [comment]
Marking this resolved. I believe it's working now.
