### ISSUE TITLE
Allow to manually set micropub endpoint and token

### ISSUE THREAD

**Issue by sknebel** [keithjgrant/omnibear#37]
Inspired by discussion in [#indieweb-dev today](https://chat.indieweb.org/dev/2017-10-26#t1509034462869000):

Since omnibear can really easily be run locally (as in, it always runs locally) it's a prime candidate to test micropub endpoints during development, running locally as well. Getting a token using online services can then be a bit tricky to set up. It would be helpful if one could set the micropub endpoint URL and token manually and totally avoid the discovery and authorization stage. 

UI wise, I image in a "developer" or "advanced" option as an alternative to entering the homepage URL for the normal IndieAuth flow.

**Comment by keithjgrant** [comment]
That makes sense. 
Under the hood, Omnibear stores these values in localStorage, so if you can get to a debugger for the omnibear window (right-click -> Inspect in Chrome), you can manually set the needed localStorage keys in the browser console:

`localStorage.setItem('token', tokenString);
localStorage.setItem('domain', 'http://yourdomain.com');
localStorage.setItem('micropubEndpoint', endpointUrl);`


I’m pretty sure those three are the only keys you’d need. It also sets a `tokenEndpoint` and `authEndpoint` but I don’t think it would need those once the token is set.

**Comment by keithjgrant** [comment]
I probably won’t add this feature directly to the app, but I do want to document this in a `developers.md` (or similar) readme here in this repository.

**Comment by sknebel** [comment]
Would you accept a PR adding it?

**Comment by keithjgrant** [comment]
of course!

**Comment by keithjgrant** [comment]
Options added to the new settings page
