### ISSUE TITLE
Add Facebook support

### ISSUE THREAD

**Issue by keithjgrant** [keithjgrant/omnibear#4]
Similar to twitter.com, add support for entries on facebook.com

**Comment by keithjgrant** [comment]
Adding help wanted tag, as I don’t have a facebook account. I'll create one, but if anybody is interested in picking this up first, it should be pretty straightforward.

You can see how twitter.com integration works here: https://github.com/keithjgrant/omnibear/blob/master/src/page/entry.js#L29-L31. Given the clicked element (e.target), traverse up to find the wrapping element for that entry, then find the corresponding URL.

**Comment by terminalpixel** [comment]
I'll have a look at it :)

**Comment by terminalpixel** [comment]
Managed to get it working more or less.

Do you want just the change in /src committed or with the built changes as well?

**Comment by keithjgrant** [comment]
Awesome! Just the /src is fine. But don't worry about it if you've already got commits w/ the build
