### ISSUE TITLE
Discover endpoints using Link header

### ISSUE THREAD

**Issue by myfreeweb** [keithjgrant/omnibear#41]
Hi! Tried the extension, got this:

> Missing micropub data on https://unrelenting.technology/. Please ensure the following links are present: authorization_endpoint, token_endpoint, micropub

with this header:

```
Link: <https://unrelenting.technology/webmention>; rel=webmention, <https://unrelenting.technology/micropub>; rel=micropub, <https://unrelenting.technology/login>; rel="token_endpoint", <https://indieauth.com/auth>; rel="authorization_endpoint", <https://switchboard.p3k.io>; rel=hub, <https://unrelenting.technology/>; rel=self
```

`micropub-helper` actually supports Link headers, but it seems you use some server-side app to authenticate (is it open source?)

**Comment by grantcodes** [comment]
Have you tried compiling omnibear from the source here? GitHub has the updated `micropub-helper` library but the released version doesn't.

I haven't really fully tested the `micropub-helper` header handling but I think it should work

**Comment by myfreeweb** [comment]
Oh. It's broken there. It requires the `rel` to be quoted. I'll send a fix to micropub-helper.

**Comment by myfreeweb** [comment]
https://github.com/grantcodes/micropub/pull/5 — that works, but now I'm at this super helpful screen :)

![Error fetching token from token endpoint object Object](https://user-images.githubusercontent.com/208340/32504880-eca1d926-c3f1-11e7-9f70-2c62b2ea079c.png)

Looks like I'll need to update my token endpoint to return JSON.

**Comment by grantcodes** [comment]
Again the token fetching should be handled by `micropub-helper` and it should support json and querystrings. What does your endpoint return?

**Comment by myfreeweb** [comment]
It returned a 406 error because Omnibear sent `Accept: application/json`

**Comment by grantcodes** [comment]
Ah ok that is actually from here: https://github.com/grantcodes/micropub/blob/05541c028e218e46529eac7e4ff947c720553bfa/src/main.js#L168

**Comment by myfreeweb** [comment]
Yeah, looks like you do parse querystrings, so it should be `application/json, application/x-www-form-urlencoded`

**Comment by grantcodes** [comment]
Yeah, if you could test it that would be great and I'll push an update

**Comment by myfreeweb** [comment]
[It works](https://unrelenting.technology/likes/2017-11-07-17-18-17)!

**Comment by grantcodes** [comment]
Sweet! I'll update all those accept headers and push another `micropub-helper` update
