### ISSUE TITLE
Provide compiled extensions in releases

### ISSUE THREAD

**Issue by cweiske** [keithjgrant/omnibear#46]
Instead of providing the source code as .zip in the github releases section, please provide the compiled extensions so that one can install them without using the stores.

**Comment by keithjgrant** [comment]
I’ve been tagging releases with the git CLI. Should I do this through the Github interface instead (i.e. uploading the zip file manually)?

**Comment by cweiske** [comment]
If I checkout a git tag, I still need to compile the JS and such.
The .zip file that you upload to the play store or mozilla addons page can be used directly, which is why having that in the releases (manually uploaded or via API) would be nice.

**Comment by keithjgrant** [comment]
Oh, I see. You want me to make the zips available for download somewhere?

There are all archived in the [zips folder](https://github.com/keithjgrant/omnibear/tree/master/zips), but I could expose that better somehow.

**Comment by cweiske** [comment]
I do not think that distribution files should be part of the source code repository itself.
-- 
Regards/Mit freundlichen Grüßen
Christian Weiske

**Comment by keithjgrant** [comment]
Provided with [v1.0.0](https://github.com/keithjgrant/omnibear/releases/tag/v1.0.0). I’ll try and do this from now on with all future releases
