### ISSUE TITLE
Make selected mode more recognizable

### ISSUE THREAD

**Issue by cweiske** [keithjgrant/omnibear#49]
I find it hard to see which of the modes - "New note" or "Current page" is active, because they do not look like normal tab elements, and neither of them is bold when selected.

![2017-11-29 omnibear active](https://user-images.githubusercontent.com/59036/33388635-c7f193aa-d530-11e7-9746-153a862fff3e.png)

**Comment by keithjgrant** [comment]
![screen shot 2018-01-23 at 1 49 35 pm](https://user-images.githubusercontent.com/410794/35294338-4c39aec0-0044-11e8-87dc-b2c573f9a4a9.png)

**Comment by keithjgrant** [comment]
How’s that? 😀

**Comment by cweiske** [comment]
Looks good.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
