### ISSUE TITLE
Default to "current page" mode

### ISSUE THREAD

**Issue by cweiske** [keithjgrant/omnibear#50]
To be able to quickly like a page, the "current page" mode should be default.

Or omnibear should have an option to make it default :)

Currently I have to click on the omnibear icon, then "current page", then on the star icon. The second click would not be necessary if "current page" was default.

**Comment by keithjgrant** [comment]
I like this idea.

I've been wanting to add a Settings page anyway, so this makes sense to add. In the meantime, you can use the context menu to do this. Right click the page -> "Reply to entry" will open the Omnibear screen with "current page" mode enabled.
