### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by grantcodes** [keithjgrant/omnibear#69]
Got a new PC so been trying out Edge.

It's really easy to get Omnibear working, just a case of adding a few more values to the manifest and changing all `chrome.` to `browser.`

I need to make sure that is safe to do for all browsers though, but I think they all support that.

**Comment by grantcodes** [comment]
Ok so in unrelated testing chrome still uses the `chrome` variable but you can easily reassign that to `window.browser` and it should all just work.

**Comment by keithjgrant** [comment]
This should work on the master branch now
