### ISSUE TITLE
Settings checkbox not showing up on Chrome

### ISSUE THREAD

**Issue by dougbeal** [keithjgrant/omnibear#72]
[Settings checkbox not showing up on Chrome](https://github.com/keithjgrant/omnibear)

# Settings checkbox not showing up on Chrome

Settings checkbox not showing up on Chrome ![](https://dougbeal.com/wp-content/uploads/2018/06/omnibear-nocheckboxes.png)

(Originally published at: https://crw.moe/b/RL)

**Comment by dougbeal** [comment]
Its an issue with Mojave and Chrome.  Changing the font size will cause it to display in a webpage, but doesn't help with an extension

**Comment by keithjgrant** [comment]
It looks like this is a bug in Chrome on Mojave. You can fix the issue with [this plugin](https://chrome.google.com/webstore/detail/mojave-checkbox-fix/ihlgehdlkphgngjfagonbeoepadbdaae/reviews) until they resolve the issue. Closing as this doesn't appear to be a bug in Omnibear.
