### ISSUE TITLE
What if omnibear has a settings page on your website to sync settings between...

### ISSUE THREAD

**Issue by dougbeal** [keithjgrant/omnibear#73]
What if omnibear has a settings page on your website to sync settings between browsers?

(Originally published at: https://crw.moe/b/SU)

**Comment by grantcodes** [comment]
I think this would be very difficult to achieve. 

The most likely way to get any sort of setting synchronization to work on the indieweb would be with [micropub queries](https://indieweb.org/Micropub-brainstorming#Query_for_post_list)

The other option is also using the browser synced storage for the settings. Omnibear currently uses localstorage but extensions are recommended to use the webextension storage api, which has a syncing option

**Comment by keithjgrant** [comment]
While this is an interesting idea, I don’t think it would be worth the effort on my part. Closing for now.
