### ISSUE TITLE
not handling errors from token endpoint

### ISSUE THREAD

**Issue by aaronpk** [keithjgrant/omnibear#8]
The extension got a 500 server error from my token endpoint (my fault mostly), but it thought it was successful and stored the string `"null"` for the access token. It looked like I was logged in, but it would send `"null"` as the access token when I posted.

**Comment by keithjgrant** [comment]
I catch the error now and display it on the open page (omnibear.com/auth/success). I also removed the `Accept: application/json` header that you mentioned in the indieweb chat.

0.4.0 is being published now to the Chrome web store (Google says this may take up to 60 mins). If you have a chance to verify with your auth endpoint, that would be great.

**Comment by aaronpk** [comment]
oh! I wasn't suggesting removing the `Accept: application/json` header, just making sure that if you send it, then you expect to receive JSON. (I'm hoping to be able to transition the IndieAuth spec to use JSON responses everywhere so that it's compatible with OAuth 2.0. My endpoints will return form-encoded by default and JSON if requested, which is how we can maintain backwards compatibility.) What I'm trying to do with my clients and servers now is handle both form-encoded responses and JSON responses depending on the content type headers.

**Comment by keithjgrant** [comment]
Ah, yeah indieauth.com still returns formencoded, so I am catering to that. I'll keep an eye for the update there, then change mine to JSON
