### ISSUE TITLE
omnibear mangles mastodon uri’s https://pdx.social/@dejus/101744380498713295
-&gt; https://dejus/101744380498713295

### ISSUE THREAD

**Issue by dougbeal** [keithjgrant/omnibear#87]
omnibear mangles mastodon uri’s https://pdx.social/@dejus/101744380498713295
-&gt; https://dejus/101744380498713295

(Originally published at: https://crw.moe/t/1hU)

**Comment by keithjgrant** [comment]
duplicates #78
